### ISSUE TITLE
Readme suggestions

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry-holding/device-gps#8]
1) Should we mention that only MongoDB is supported? Or can we say Redis too? Is there are Redis database cleanup script ?
2) Should you comment on the device name and how to change? device-gps-go01/100

**Comment by alexcourouble** [comment]
1. There is no Redis clean up script yet. Once Redis is fully supported, the gps-device will automatically work. At that point we can modify the README to be more specific with DB cleanup

2. Do you think the user would want to change the name? `device-gps-go01` follows the edgex device naming convention.
